version: '3.4'

services:
  samba:
    image: dperson/samba
    container_name: samba1
    environment:
      TZ: 'EST5EDT'
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    read_only: false
    tmpfs:
      - /tmp
    restart: unless-stopped
    stdin_open: true
    tty: true
#    volumes:
#      - /mnt:/mnt:z
#      - /mnt2:/mnt2:z
    command: '-s "mnt;/mnt" -s "mnt2;/mnt2;yes;no;no;bob" -u "bob;bobspasswd" -p'
    networks:
      - mynet

networks:
  mynet:
    driver: bridge